language: nodejs

before_script:
- cd client/
- npm i npm@latest -g
- npm install -g codecov
- npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run build
- npm run test
- codecov